import { defineType, defineField } from "sanity";

export const espaceEventsPage = defineType({
  name: "espaceEventsPage",
  title: "Page Espace Events",
  type: "document",
  groups: [
    { name: "hero", title: "1. Hero", default: true },
    { name: "trust", title: "2. Bandeau crédibilité" },
    { name: "venue", title: "3. La salle (capacités)" },
    { name: "intro", title: "4. Description" },
    { name: "packs", title: "5. Pack Celebration (cérémonies)" },
    { name: "packsFiesta", title: "6. Pack Fiesta (soirées)" },
    { name: "notYetDecided", title: "7. Bloc \"Pas encore décidé\"" },
    { name: "occasions", title: "8. Occasions" },
    { name: "alacarte", title: "9. À la carte" },
    { name: "locationOnly", title: "10. Location seule (tarifs jour)" },
    { name: "gallery", title: "11. Galerie" },
    { name: "testimonials", title: "12. Témoignages" },
    { name: "conditions", title: "13. Conditions" },
    { name: "faq", title: "14. FAQ" },
    { name: "finalCta", title: "15. CTA final" },
    { name: "otherServices", title: "16. Autres services (cross-sell)" },
    { name: "sticky", title: "Sticky CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "heroSection", group: "hero" }),
    defineField({ name: "trustBar", title: "Bandeau crédibilité", type: "trustBarSection", group: "trust" }),
    defineField({ name: "venue", title: "Salle (capacités, plan, infos)", type: "venueSection", group: "venue" }),
    defineField({ name: "intro", title: "Description", type: "aboutSection", group: "intro" }),
    defineField({ name: "packs", title: "Pack Celebration (3 niveaux : Classic, Premium, Prestige)", type: "packsSection", group: "packs", description: "Pour les cérémonies assises (mariages civils, henné, baptêmes…). Filtrer par 'Celebration'." }),
    defineField({ name: "packsFiesta", title: "Pack Fiesta (soirées festives)", type: "packsSection", group: "packsFiesta", description: "Pour les soirées debout (anniversaires, baby showers, EVJF…). Filtrer par 'Fiesta'." }),
    defineField({ name: "notYetDecided", title: "Bloc d'aide à la décision", type: "ctaSection", group: "notYetDecided", description: "Bloc CTA intermédiaire entre les 2 packs (ex : \"Pas encore décidé ? Comparez ou réservez une visite.\")." }),
    defineField({ name: "occasions", title: "Occasions (henné, baptême, EVJF…)", type: "ceremoniesSection", group: "occasions" }),
    defineField({ name: "alacarte", title: "Options à la carte", type: "aLaCarteSection", group: "alacarte" }),
    defineField({ name: "locationOnly", title: "Tarifs location seule (par jour)", type: "locationPricingSection", group: "locationOnly" }),
    defineField({ name: "gallery", title: "Galerie de la salle", type: "gallerySection", group: "gallery" }),
    defineField({ name: "testimonials", title: "Témoignages clients", type: "testimonialsSection", group: "testimonials" }),
    defineField({ name: "conditions", title: "Conditions de location", type: "conditionsSection", group: "conditions" }),
    defineField({ name: "faq", title: "FAQ Espace Events", type: "faqSection", group: "faq" }),
    defineField({ name: "finalCta", title: "CTA final (visiter la salle)", type: "ctaSection", group: "finalCta" }),
    defineField({ name: "otherServices", title: "Cross-sell vers Mariage / Pro", type: "crossServicesSection", group: "otherServices" }),
    defineField({ name: "stickyCta", title: "Bouton flottant", type: "stickyCtaSection", group: "sticky" }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Page Espace Events" }) },
});
