import { defineType, defineField } from "sanity";

export const evenementPage = defineType({
  name: "evenementPage",
  title: "Page Entreprises",
  type: "document",
  // Ordre des groupes = ordre exact des sections sur la page Entreprises.
  // Les sections non affichées sont regroupées en fin, préfixées « (masqué) ».
  groups: [
    { name: "hero", title: "1. Bandeau d'ouverture", default: true },
    { name: "lieux", title: "2. Trois lieux d'intervention" },
    { name: "packs", title: "3. Les quatre packs" },
    { name: "budget", title: "4. Comment est construit le budget" },
    { name: "scope", title: "5. Pourquoi Aïssa Events" },
    { name: "process", title: "6. Notre méthode" },
    { name: "portfolio", title: "7. Preuves / Réalisations" },
    { name: "finalCta", title: "8. CTA final" },
    { name: "form", title: "9. Formulaire de qualification" },
    { name: "trust", title: "— (masqué) Bandeau crédibilité" },
    { name: "intro", title: "— (masqué) Intro / signature musicale" },
    { name: "usecases", title: "— (masqué) Formats pro" },
    { name: "alacarte", title: "— (masqué) À la carte" },
    { name: "gallery", title: "— (masqué) Galerie" },
    { name: "timeline", title: "— (masqué) Timeline" },
    { name: "testimonials", title: "— (masqué) Témoignages" },
    { name: "faq", title: "— (masqué) FAQ" },
    { name: "sticky", title: "— (masqué) Bouton flottant" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "heroSection", group: "hero" }),
    defineField({ name: "trustBar", title: "Bandeau crédibilité", type: "trustBarSection", group: "trust" }),
    defineField({ name: "intro", title: "Intro / signature musicale", type: "aboutSection", group: "intro" }),
    defineField({ name: "usecases", title: "Formats pro (4 cartes)", type: "processSection", group: "usecases", description: "Utilise le format Process (italique + suite + description). Idéal pour 4 formats type Afterworks / Soirées clients / Lancements / Séminaires." }),
    defineField({ name: "packs", title: "Pack Ambiance & autres", type: "packsSection", group: "packs" }),
    defineField({ name: "budget", title: "Comment est construit le budget", type: "budgetSection", group: "budget" }),
    defineField({ name: "process", title: "Process (étapes)", type: "processSection", group: "process" }),
    defineField({ name: "lieux", title: "Lieux (options)", type: "lieuxSection", group: "lieux" }),
    defineField({ name: "scope", title: "Périmètre sur-mesure (6 prestations)", type: "conditionsSection", group: "scope", description: "Liste de prestations détaillées (utilise le format Conditions : titre + description)." }),
    defineField({ name: "alacarte", title: "Services à la carte", type: "aLaCarteSection", group: "alacarte" }),
    defineField({ name: "gallery", title: "Galerie événements", type: "gallerySection", group: "gallery" }),
    defineField({ name: "portfolio", title: "Portfolio (études de cas)", type: "caseStudiesSection", group: "portfolio" }),
    defineField({ name: "timeline", title: "Timeline (planning)", type: "timelineSection", group: "timeline" }),
    defineField({ name: "testimonials", title: "Témoignages clients", type: "testimonialsSection", group: "testimonials" }),
    defineField({ name: "faq", title: "FAQ Événement", type: "faqSection", group: "faq" }),
    defineField({ name: "finalCta", title: "CTA final", type: "ctaSection", group: "finalCta" }),
    defineField({ name: "qualificationForm", title: "Formulaire de qualification", type: "qualificationFormSection", group: "form" }),
    defineField({ name: "stickyCta", title: "Bouton flottant", type: "stickyCtaSection", group: "sticky" }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Page Entreprises" }) },
});
