import { defineType, defineField } from "sanity";

export const evenementPage = defineType({
  name: "evenementPage",
  title: "Page Événement",
  type: "document",
  groups: [
    { name: "hero", title: "1. Hero", default: true },
    { name: "trust", title: "2. Bandeau crédibilité" },
    { name: "intro", title: "3. Intro" },
    { name: "usecases", title: "4. Formats pro" },
    { name: "packs", title: "5. Packs" },
    { name: "process", title: "6. Process" },
    { name: "lieux", title: "7. Lieux" },
    { name: "scope", title: "8. Périmètre (sur-mesure)" },
    { name: "alacarte", title: "9. À la carte" },
    { name: "gallery", title: "10. Galerie" },
    { name: "portfolio", title: "11. Portfolio" },
    { name: "timeline", title: "12. Timeline" },
    { name: "testimonials", title: "13. Témoignages" },
    { name: "faq", title: "14. FAQ" },
    { name: "finalCta", title: "15. CTA final" },
    { name: "sticky", title: "Sticky CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "heroSection", group: "hero" }),
    defineField({ name: "trustBar", title: "Bandeau crédibilité", type: "trustBarSection", group: "trust" }),
    defineField({ name: "intro", title: "Intro / signature musicale", type: "aboutSection", group: "intro" }),
    defineField({ name: "usecases", title: "Formats pro (4 cartes)", type: "processSection", group: "usecases", description: "Utilise le format Process (italique + suite + description). Idéal pour 4 formats type Afterworks / Soirées clients / Lancements / Séminaires." }),
    defineField({ name: "packs", title: "Pack Ambiance & autres", type: "packsSection", group: "packs" }),
    defineField({ name: "process", title: "Process (étapes)", type: "processSection", group: "process" }),
    defineField({ name: "lieux", title: "Lieux (options)", type: "lieuxSection", group: "lieux" }),
    defineField({ name: "scope", title: "Périmètre sur-mesure (6 prestations)", type: "conditionsSection", group: "scope", description: "Liste de prestations détaillées (utilise le format Conditions : titre + description)." }),
    defineField({ name: "alacarte", title: "Services à la carte", type: "aLaCarteSection", group: "alacarte" }),
    defineField({ name: "gallery", title: "Galerie événements", type: "gallerySection", group: "gallery" }),
    defineField({ name: "portfolio", title: "Portfolio (études de cas)", type: "caseStudiesSection", group: "portfolio" }),
    defineField({ name: "timeline", title: "Timeline (planning)", type: "timelineSection", group: "timeline" }),
    defineField({ name: "testimonials", title: "Témoignages clients", type: "testimonialsSection", group: "testimonials" }),
    defineField({ name: "faq", title: "FAQ Événement", type: "faqSection", group: "faq" }),
    defineField({ name: "finalCta", title: "CTA final", type: "ctaSection", group: "finalCta" }),
    defineField({ name: "stickyCta", title: "Bouton flottant", type: "stickyCtaSection", group: "sticky" }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Page Événement" }) },
});
