import { defineType, defineField } from "sanity";

export const mariagePage = defineType({
  name: "mariagePage",
  title: "Page Mariage",
  type: "document",
  groups: [
    { name: "hero", title: "1. Hero", default: true },
    { name: "trust", title: "2. Bandeau crédibilité" },
    { name: "intro", title: "3. Intro" },
    { name: "packs", title: "4. Packs mariage" },
    { name: "themes", title: "5. Thèmes" },
    { name: "ceremonies", title: "6. Cérémonies" },
    { name: "lieux", title: "7. Lieux" },
    { name: "timeline", title: "8. Timeline" },
    { name: "alacarte", title: "9. À la carte" },
    { name: "gallery", title: "10. Galerie" },
    { name: "portfolio", title: "11. Portfolio" },
    { name: "testimonials", title: "12. Témoignages" },
    { name: "conditions", title: "13. Conditions" },
    { name: "faq", title: "14. FAQ" },
    { name: "finalCta", title: "15. CTA final" },
    { name: "sticky", title: "Sticky CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "hero", title: "Hero", type: "heroSection", group: "hero" }),
    defineField({ name: "trustBar", title: "Bandeau crédibilité", type: "trustBarSection", group: "trust" }),
    defineField({ name: "intro", title: "Intro / À propos", type: "aboutSection", group: "intro" }),
    defineField({ name: "packs", title: "Packs mariage", type: "packsSection", group: "packs" }),
    defineField({ name: "themes", title: "Thèmes (orientale, bohème, etc.)", type: "themesSection", group: "themes" }),
    defineField({ name: "ceremonies", title: "Cérémonies (types)", type: "ceremoniesSection", group: "ceremonies" }),
    defineField({ name: "lieux", title: "Lieux (options)", type: "lieuxSection", group: "lieux" }),
    defineField({ name: "timeline", title: "Timeline préparation", type: "timelineSection", group: "timeline" }),
    defineField({ name: "alacarte", title: "Services à la carte", type: "aLaCarteSection", group: "alacarte" }),
    defineField({ name: "gallery", title: "Galerie mariages", type: "gallerySection", group: "gallery" }),
    defineField({ name: "portfolio", title: "Portfolio (études de cas)", type: "caseStudiesSection", group: "portfolio" }),
    defineField({ name: "testimonials", title: "Témoignages mariés", type: "testimonialsSection", group: "testimonials" }),
    defineField({ name: "conditions", title: "Conditions de réservation", type: "conditionsSection", group: "conditions" }),
    defineField({ name: "faq", title: "FAQ Mariage", type: "faqSection", group: "faq" }),
    defineField({ name: "finalCta", title: "CTA final", type: "ctaSection", group: "finalCta" }),
    defineField({ name: "stickyCta", title: "Bouton flottant", type: "stickyCtaSection", group: "sticky" }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Page Mariage" }) },
});
